### ISSUE TITLE
Plugin does not seem to pick up changes due to gradle caching or something

### ISSUE THREAD

**Issue by cpoulsen-dezide** [gigaSproule/swagger-gradle-plugin#32] opened 2017-10-31 07:28 UTC
Hi,

I have noticed that the plugin does not seem to pick up changes in the source files after a successful build.

Executing: `gradlew clean gSD` generates a new swagger.json, but the contents are stale (identical to the previous run). If I run the command as `gradlew --no-daemon clean gSD` the expected (updated) result is generated.

This happens with gradle 4.1 and 4.2.1 (and possibly others, I just tried the previous version to confirm that it was not introduced in 4.2.1).

I'm not entirely sure, but I guess that some gradle task definition magic is incorrect as the gradle team seems to have been focusing on more aggressive caching in the 4.x series.

**Comment by set321go** [comment] 2017-10-31 15:23
The plugin is decidedly dumb when it comes to build caching, in my experience (gradle 4.1) the plugin runs every time regardless of changes. Can you provide a bit more details about your project, * what other plugins are you using?
* do you have source sets defined in your project?
* do the modified source files exist in the build directory prior to the `swagger-gradle-plugin` running?
* By default this plugin dependsOn the classes task

**Comment by gigaSproule** [comment] 2017-10-31 18:36
As @set321go has pointed out, there is no input directory specified so it doesn't cache (or at least shouldn't). If you can provide more info, I'm sure we can solve it.

**Comment by cpoulsen-dezide** [comment] 2017-11-01 07:06
Hi,

- Other plugins: java, org.springframework.boot
- No other source sets
- I used the clean target prior to the generateSwaggerDocumentation task - even manually removing the generated json/yaml prior to generation results in stale contents

I've never noticed any hiccups with the plugin in other projects (but they are using earlier gradle / plugin versions, that was why my guess was it had something to do with more aggressive gradle caching in the recent versions)

I will try with v0.1.9

**Comment by cpoulsen-dezide** [comment] 2017-11-06 14:29
Hi, 

I've had a deeper look into this. My expections to the plugin was that it automatically plugged into the build at the correct phase. It seems that it does not, instead it requires one to explicitly call "generateSwaggerDocumentation" - In the examples above I discovered there was at least one other module explicitly depending on the generateSwaggerDocumentation task in the module, so that may have been why the plugin was seeing the wrong stuff.

Is there a way to plug in the "generateSwaggerDocumentation" task so its output is automatically generated and automatically included in the jar?

My gradle-fu is not particular strong, but I've tried to reverse the dependency direction by adding task dependencies in the gradle script, however that leads to circular dependencies as the plugin declares a "dependsOn" in the opposite direction. The only way I found around this is to alter part of the plugin apply to:
```
        project.task(GenerateSwaggerDocsTask.TASK_NAME, type: GenerateSwaggerDocsTask )
        project.tasks.classes.finalizedBy GenerateSwaggerDocsTask.TASK_NAME
```
That seems to work. However I cannot figure out how to achieve the same without altering the plugin, suggestions are very welcome!

**Comment by set321go** [comment] 2017-11-06 15:47
most plugins that are not OTB gradle will not hook into a lifecycle automatically, you would typically achieve what your after with the `dependsOn` as you mentioned. In my projects i use `build.dependsOn tasks.generateSwaggerDocumentation` at the bottom of the gradle file

**Comment by delego-wlritchi** [comment] 2017-11-29 13:41
I'm also experiencing this issue with version 0.1.9, on Gradle 3.2 as well as 4.3.1. If a daemon is running, and that daemon has previously run the generateSwaggerDocumentation task, future runs of the task in that daemon will succeed, but they'll produce a stale result. I'm using `generateSwaggerDocumentation.dependsOn classes` to hook into the lifecycle, and `gradle clean generateSwaggerDocumentation` on the command line.

I'll try to set up a minimal reproduction repo when I have a chance.

**Comment by gigaSproule** [comment] 2017-11-30 22:41
It should always run again. The task doesn't define an output, so how the daemon knows it is up-to-date seems odd. Do you definitely see a `up-to-date` in the console for the `generateSwaggerDocumentation` task? If you can post here how you've got the plugin configured or link to the repo (when you've done it), I can see if I get the same issue.

**Comment by cpoulsen-dezide** [comment] 2017-12-01 11:38
The task is running as far as I remember, it simply looks like the task "inputs" are stale / not in sync with what is actually present.

**Comment by gigaSproule** [comment] 2017-12-11 22:46
Just managed to try this out and I was able to replicate it. Very odd...

**Comment by sergeijakovlev** [comment] 2017-12-12 16:13
In our case cleaning the project beforehand does not help. In fact, even completely removing all build catalogs and `.gradle` catalog does not seem to help - as long the build is performed with the same daemon, the same (stale) Swagger files are generated.

**Comment by gigaSproule** [comment] 2017-12-12 16:26
That is really odd. I'll see if the behaviour is the same with the re-write for issue #30.

**Comment by gigaSproule** [comment] 2017-12-13 12:19
I just had the same issue with [this license plugin](https://github.com/hierynomus/license-gradle-plugin). I had to delete the `.gradle` folder in the root of the project. I had created 2 new classes and needed to add headers to them. The plugin would complain about them not having headers, but refused to add them in.

**Comment by OlivierMary** [comment] 2017-12-31 16:08
Hi,
Same with gradle 4.4.1, Have to kill gradle daemon process and restart generateSwaggerDocumentation to have last changes of classes.

Maybe : https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon
But not recommended...

**Comment by OlivierMary** [comment] 2017-12-31 16:28
Work with `./gradlew --no-daemon clean generateSD `

But not in IntelliJ [(see why)](https://stackoverflow.com/questions/25422163/how-to-disable-gradle-daemon-in-intellij-idea), so only with Terminal.

**Comment by cslee00** [comment] 2018-01-11 02:31
Just logged the same issue in #37 - the internals of the plugin (the Maven portion) modify the classloader classpath & load the classes to analyze them; once loaded they won't be loaded again.

Running Gradle with --no-daemon is a workaround for some cases, the proper fix is to provide an isolated, disposable classloader and run in there.

**Comment by gigaSproule** [comment] 2018-02-07 22:43
With the latest release, I can't replicate this anymore. If someone can replicate this by the end of the month, the please state otherwise I will assume it's fixed and will close this.

**Comment by cpoulsen-dezide** [comment] 2018-02-08 08:03
The issue is still present here with plugin version 1.0.0

I tried with the gradle we are using in the project (4.3.1) and the most recent (4.5.1) and the behavior is unfortunately still like originally reported.

**Comment by fmotrifork** [comment] 2018-02-08 14:24
I cannot reproduce this anymore with Gradle 3.4

Please note the plugin is released as 1.0.0. And that there was already a 1.0.0 released before _the big rewrite._

@cpoulsen-dezide Try to clear all your gradle/m2 caches and make sure that you have the 1.0.0 version that was released 06 February 2018.

**Comment by gigaSproule** [comment] 2018-02-08 21:07
@fmotrifork That would be my bad. I was messing around with the release setup and my laptop screwed up. Really need to get a new one as this thing is ancient.

**Comment by OlivierMary** [comment] 2018-02-08 21:24
@gigaSproule All good for me with v1.0.0 and gradle 4.5.1.

Thanks.

**Comment by TimoFedd** [comment] 2018-02-16 12:06
I have still the problem with v1.0.0 and gradle 4.5.1
It sems to be a problem with an in-mermory cache mechanism because
if i use the --no-daemon flag it works.

**Comment by gigaSproule** [comment] 2018-02-16 19:08
@TimoFedd Do you still get the issue with the latest v1.0.2?

**Comment by cpoulsen-dezide** [comment] 2018-02-19 11:39
@gigaSproule I've managed to convince myself that this is working like expected again (Gradle 4.5.1 and plugin version 1.0.2)

**Comment by gigaSproule** [comment] 2018-02-20 21:42
I'll keep this open still until the end of the month, just in case Gradle can convince you otherwise!

**Comment by TimoFedd** [comment] 2018-02-26 14:29
@gigaSproule with 1.0.2 and gradle 4.5.1 it works! :)

**Closed** 2018-03-03 15:36 UTC
Labels: bug

**Comment by Tristan-Louvre** [comment] 2018-08-01 11:31
@gigaSproule, with 1.0.4, gradle 4.9.0, intellij 2018.1.5 and Windows 10 I have the same issue with the gradle daemon being held open. It prevents me from successfully cleaning my build. 

Running the following command twice in a row results in build failure:

`gradlew clean generateSwaggerDocumentation build`

I place my swagger in the build output directory as I want it to be cleaned when the build dir gets nuked:

`swaggerDirectory = "${buildDir}/swagger"`

The directory within the build dir gets marked as [main], this is possibly because of how I add the file to the war?

![image](https://user-images.githubusercontent.com/16668501/43519094-64f3353c-958e-11e8-8d9b-3bef29731390.png)

```
war {
    from("${buildDir}/swagger") {
        include 'swagger.json'
    }
}
```

Finally, this occurs on a multi-module project.

Should we re-open this issue or should I make another?

**Comment by gigaSproule** [comment] 2018-08-03 07:00
I imagine what's happening is the war task is running before generate. Can you try breaking the steps out into separate runs to prove our disprove it?
