### ISSUE TITLE
Definitions in generated swagger.json contains more than model types

### ISSUE THREAD

**Issue by dcp65** [gigaSproule/swagger-gradle-plugin#47] opened 2018-02-15 16:34 UTC
This seems to have crept in since I upgraded from 0.1.9 to 1.0.2.

Previously, the 'definitions' section of my generated `swagger.json` only included classes from my project's 'api-model' module.

Now, a host of unrelated classes, that should never be exposed in API documentation, are appearing. 

I have now rolled back to 0.1.9 and I'm only seeing the expected definition classes.

**Comment by set321go** [comment] 2018-02-16 00:05
Thanks I can see what the problem is. 

If `mypackage` is specified in the locations property on the plugin but `external` is not, you expect only `MyModel` to appear in the `swagger.json` correct?

```
mypackage.MyModel {
  External type
}

external.External {
  String value
}
```

How do you expect the `swagger.json` to reference that other type?

**Comment by dcp65** [comment] 2018-02-16 07:56
@set321go Correct, I expect only models that are referenced by my APIs to appear in the definitions section.

Sorry, but I don't understand what you mean by 'external'. There's no reference to 'external' in the project README.

**Comment by set321go** [comment] 2018-02-16 16:02
external was just an example of a package/class that was Referenced by your API model and 'external dependency'

**Comment by dcp65** [comment] 2018-02-16 17:27
OK, I think I understand. If my API explicitly references an external class - like `FileInputStream` - then I expect it to appear in the definitions.

However, the problem I'm seeing is that with version 1.0.2 of the plugin, a whole host of classes appear that aren't referenced by the APIs at all.

**Comment by gigaSproule** [comment] 2018-02-16 18:52
Can you give a dummy example so we can replicate this?

**Comment by set321go** [comment] 2018-02-16 21:27
So what i'm seeing with this version is that any classes that are part of a model object that are not java packages are put into the definitions regardless of what packages you specify in locations. I don't know what the behaviour was previously or how one would reference those other types if they didn't appear there, it's essentially referencing all types that make up the model hierarchy regardless of whether those types are directly referenced in your api classes/annotations.

**Comment by set321go** [comment] 2018-02-18 18:30
I think the problem is caused by `JaxrsReader L323 - L326` & `SpringMvcApiReader L249 - L252` and change from wrapping the maven plugin to being in gradle changed the classloader the generation code is being exposed to. I do wonder if the behaviour that the `swagger-gradle-plugin` used to exhibit was the same as if you had run the `swagger-maven-plugin` in maven.

I have been pretty busy so i've not had time to create some tests to experiment with this, hopefully by the end of the week i can allocate some time to it.

**Comment by dcp65** [comment] 2018-02-19 10:42
OK, looks like you've got this, but just to recap: 

All my model classes are in the same package. Each classname ends with 'Model'. When I generate swagger with 0.1.9, I get 18 definitions, corresponding to each 'Model' file.

When I generate with 1.0.2, I get 122 definitions, none of which appear in the models package. Many of them aren't even directly declared in my project, but are brought in via dependencies.

**Comment by gigaSproule** [comment] 2018-04-30 15:47
I've tried this with the tests with both the classes being under the `location` package but not used and outside of the `location` package and neither were being included.

Example structure:
```
- com.benjaminsproule.swagger.gradleplugin
| - ignore
| | - IgnoredModel
| - test
| | - model
| | | - RequestModel
| | | - ResponseModel
| | | - SubResponseModel
| | | - UnusedModel
```
Example config:
```
apiSource {
    locations = ['com.benjaminsproule.swagger.gradleplugin.test']
    schemes = ['http']
    info {
        title = project.name
        version = '1'
        license {
            name = 'Apache 2.0'
        }
        contact {
            name = 'Joe Blogs'
        }
    }
    swaggerDirectory = expectedSwaggerDirectory
    host = 'localhost:8080'
    basePath = '/'
    securityDefinition {
        name = 'MyBasicAuth'
        type = 'basic'
    }
}
```

Have I got this setup right, or am I completely missing it?

**Comment by gigaSproule** [comment] 2018-04-30 16:07
Actually, I updated the tests for both JAX-RS and Spring to check the definitions and the Spring one failed. So JAX-RS is fine, but the Spring one brings in quite a few Spring classes.

**Comment by gigaSproule** [comment] 2018-04-30 16:18
Reading the JavaDoc for `@ApiOperation#response`:
```java
/**
* The response type of the operation.
* <p>
* In JAX-RS applications, the return type of the method would automatically be used, unless it is
* {@code javax.ws.rs.core.Response}. In that case, the operation return type would default to `void`
* as the actual response type cannot be known.
* <p>
* Setting this property would override any automatically-derived data type.
* <p>
* If the value used is a class representing a primitive ({@code Integer}, {@code Long}, ...)
* the corresponding primitive type will be used.
*/
```
So the Spring implementation is wrong as the tests are returning `Response` (rightly or wrongly).

**Comment by dcp65** [comment] 2018-04-30 16:29
OK. FWIW, each of my @ApiOperation annotations includes a 'response' attribute (equal to one of my model files). Those are the only classes that I expect to see in my Swagger definitions. 

I am using Spring and when I use 1.0.2 of swagger-gradle-plugin, a large number of additional classes are included in the 'definitions'. These classes _are_ referenced in my resource classes, but not as part of the API response.

**Comment by gigaSproule** [comment] 2018-04-30 16:36
Ok, so they are part of the object, but are never populated and therefore never returned?
Example:
```
class A {
    String value;
    B internalStuff;
}
```
Sorry this is dragging out, I'm just trying to make sure I create an accurate test to replicate it.

**Comment by dcp65** [comment] 2018-04-30 16:51
Here's an example:

`@Api(tags = 'Users')
@Path('/companies/{companyUid}/users')

class UserResource extends AbstractResource {
    @Autowired
    ExternalAccountService accountService
    @Autowired
    ExternalAccountStore accountStore
    @Autowired
    BookmarkService bookmarkService
    @Autowired
    UserTranslator userTranslator
    @Autowired
    MyApiRequest apiRequest

    @GET
    @ApiOperation(value = 'List users', notes = 'Returns a list of users', response = UsersModel, nickname = 'listUsers')
    @Produces('application/json')
    Response list(
            @PathParam('companyUid') String companyUid,
            @QueryParam('email') String email) {

        verifyAccess(apiRequest.sessionToken, companyUid)

        List<UserBean> users = userService.findAllByCompany(companyUid, email)

        UsersModel responseModel = new UsersModel(users: users.collect { userTranslator.build(it) })

        Response.ok().entity(responseModel).build()
    }
}`

All I expect to see in the Swagger definitions for this API is UsersModel.

Instead, the following classes are also listed:

ExternalAccountService
ExternalAccountStore
BookmarkService
UserTranslator
MyApiRequest
UserBean
SessionToken

**Comment by gigaSproule** [comment] 2018-05-02 09:10
@dcp65 I tried adding that to the spring-boot-jaxrs sample project and could not get it to replicate your behaviour. I'm going to try and create a Groovy version, to see if it's Groovy related (as I can see you are using instead of Java).

@kod4n It could very well be the case. I'll try and replicate this behaviour, fix it and then you can try the fix? I think it's probably best to assume it's the same problem until we know more.

**Comment by dcp65** [comment] 2018-05-02 10:58
@gigaSproule Yes, I am using Groovy. 

I should also say that this problem does not arise in a separate project where the API controllers are written in Kotlin.

**Comment by gigaSproule** [comment] 2018-05-02 13:41
Recreated the issue with a new sample, so will now try and create a test to replicate it.

**Comment by gigaSproule** [comment] 2018-05-02 16:10
I've added tests for Groovy and Kotlin controller classes and noticed it only happens for Groovy and Jax-RS, because the Jax-RS reader doesn't filter out methods that aren't API endpoint methods.

**Comment by gigaSproule** [comment] 2018-05-02 16:26
Fixed in a branch, just waiting for the builds to pass then I can merge it into develop

**Comment by dcp65** [comment] 2018-05-02 16:28
Fantastic. Thanks.

**Comment by gigaSproule** [comment] 2018-05-02 16:34
In IntelliJ the tests pass, but through gradle, they fail :(

**Comment by gigaSproule** [comment] 2018-05-03 10:14
Fixed it. Hadn't setup the project properly for Kotlin.

**Closed** 2018-05-23 15:30 UTC
Labels: bug
